services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      username: user
      password: pass
      database: announcetwo
      DATABASE_URL: postgres://user:pass@db:5432/announcetwo
      NODE_ENV: development
      PORT: 3000
    ports:
      - “80:3001"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    container_name: “postgres_db”
    image: postgres:10.4
    ports:
      - “5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: announcetwo
